filter:
  excluded_paths:
    - 'ieducar/tests/*'
    - 'ieducar/misc/**/*'
    - 'ieducar/Intranet/scripts/jquery'
    - 'ieducar/Intranet/scripts/scriptaculous'
    - 'ieducar/Intranet/scripts/prototype'
    - 'ieducar/Intranet/scripts/select2'
    - 'ieducar/Intranet/scripts/graficos'
    - 'ieducar/modules/Portabilis/Assets/Plugins/AjaxChosen/'
    - 'ieducar/modules/Portabilis/Assets/Plugins/Chosen/'

checks:
  php:
    code_rating: true

tools:
  php_analyzer: true
  php_changetracking: true
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cpd: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

build:
  environment:
    variables:
      APP_ENV: 'testing'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'localhost'
      DB_PORT: '5432'
      DB_DATABASE: 'scrutinizer'
      DB_USERNAME: 'scrutinizer'
      DB_PASSWORD: 'scrutinizer'
  dependencies:
    before:
      - composer new-install
  tests:
    override:
      command: "true"
  services:
    postgres: 9.5
